[application]

# App (Project) Name
name = "rust-app"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "rust-app"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = [
    "./assets/bootstrap-5.3.3-dist/css/bootstrap.css"
]

# Javascript code file
script = [
    "./assets/bootstrap-5.3.3-dist/bootstrap.bundle.js"
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
